USE test;
CREATE TABLE student(
stu_id INT AUTO_INCREMENT PRIMARY KEY,
stu_name VARCHAR(20) NOT NULL,
stu_addr VARCHAR(50),
sex VARCHAR(10) DEFAULT 'female'
)ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE partment(
part_id INT AUTO_INCREMENT PRIMARY KEY,
part_name VARCHAR(20) NOT NULL,
part_desc VARCHAR(50),
create_time DATETIME NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB DEFAULT CHARSET=utf8;